name:       high5-driver
version:    1.1.0
synopsis:   Driver application for the Internet High 5 Machine!
maintainer: Noon van der Silk <noonsilk@gmail.com>
license:    MIT
category:   Development


ghc-options: -Wall -fwarn-tabs


default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude


dependencies:
  - base >= 4.7 && < 5
  - aeson
  - async
  - bytestring
  - classy-prelude
  - free
  - lens
  - mtl
  - network
  - pipes
  - pipes-concurrency
  - pipes-websockets
  - process
  - text
  - transformers
  - websockets
  - wuss
  - yaml


library:
  source-dirs: src
  exposed-modules:
    - High5.Prelude
    - Control.High5.App
    - Control.High5.Machine
    - Control.High5.Commands


executables:
  high5-driver:
    ghc-options: -O2 -threaded
    main: Main.hs
    source-dirs: app
    dependencies:
      - high5-driver

tests:
  test:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
